{% set name = "ecell4" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/e/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 2dc781b662d8dbd33d1c07eeb2239331ab4f59a1ee6045c49541f9abce3513e4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
requirements:
  host:
    - python >=3
    - setuptools
    - pip
    - ecell4_base
    - matplotlib-base
  run:
    - ecell4_base
    - matplotlib-base
    - python >=3

test:
  imports:
    - ecell4
    - ecell4.datasource
    - ecell4.extra
    - ecell4.util

about:
  home: https://github.com/ecell/ecell4
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: An integrated software environment for multi-algorithm, multi-timescale, multi-spatial-representation simulation

extra:
  recipe-maintainers:
    - kozo2

